In [3]:
import pandas as pd
import numpy as np

In [4]:
##Load le fichier excel des réponses
data = pd.read_excel("FFQ.xlsx")
data

,CID,Q1_1,Q1_2,Q1_3,Q1_4,Q1_5,Q1_6,Q2_1,Q2_2,Q2_3,...,Q23_3,Q23_4,Q23_5,Q23_6,Q23_7,Q23_8,Q23_9,Q23_10,Q23_11,Q23_12
0,CID,1) Lait et produit laitiers - Lait entier (0.2...,1) Lait et produit laitiers - Lait écrémé (0.2...,1) Lait et produit laitiers - Yaourt (125 g),1) Lait et produit laitiers - Quark (100 g),1) Lait et produit laitiers - Fromage (100 g),1) Lait et produit laitiers - Crème (20 g),Fruits - Raisins ou raisins secs (100 g),Fruits - Pomme ou poire (1 portion),"Fruits - Pêche, abricot (1 portion)",...,Par rapport aux vitamines de substitution: - P...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - A...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - S...
1,066,1x par Sem.,1x par Sem.,2-4x par Sem.,2-4x par Sem.,2-4x par Sem.,Jamais ou <1/Mois,2-4x par Sem.,5-6x par Sem.,1-3x par Mois,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,074,Jamais ou <1/Mois,Jamais ou <1/Mois,1-3x par Mois,Jamais ou <1/Mois,1x par Jour,2-4x par Sem.,2-4x par Sem.,Jamais ou <1/Mois,Jamais ou <1/Mois,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,061,1-3x par Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,2-4x par Sem.,Jamais ou <1/Mois,2-4x par Sem.,1-3x par Mois,1x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,092,Jamais ou <1/Mois,1x par Sem.,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,2-4x par Sem.,1x par Jour,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,024,1x par Jour,Jamais ou <1/Mois,1-3x par Mois,Jamais ou <1/Mois,2-4x par Sem.,1-3x par Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,097,1x par Sem.,2-4x par Sem.,2-4x par Sem.,2-4x par Sem.,2-4x par Sem.,2-4x par Sem.,Jamais ou <1/Mois,1x par Sem.,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,094,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,2-4x par Sem.,2-4x par Sem.,1-3x par Mois,5-6x par Sem.,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,004,Jamais ou <1/Mois,Jamais ou <1/Mois,1x par Jour,Jamais ou <1/Mois,2-4x par Sem.,Jamais ou <1/Mois,1-3x par Mois,5-6x par Sem.,Jamais ou <1/Mois,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,073,2-4x par Sem.,Jamais ou <1/Mois,5-6x par Sem.,Jamais ou <1/Mois,2-4x par Sem.,1x par Sem.,Jamais ou <1/Mois,1x par Sem.,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
##Isoler les valeurs
answers = data.iloc[1:, 1:]
answers = answers.fillna(0)
answers = np.array(answers)

##Réponses différentes par question

#Trouver la question 9 (questions non-analysées après)
q9 = data.iloc[0].index.tolist().index('Q9') #nom de la colonne

#Questions 1-8
answers = data.iloc[1:, 1:q9]
answers = answers.fillna(0)
answers = np.array(answers)
answers_flat = answers.reshape(-1)
unique_answers1 = set()
for answer in answers_flat:
    unique_answers1.add(answer)
unique_answers1 = list(unique_answers1)
print(unique_answers1)

#Questions 9-23
#unique_answers2 = []
#for index in range(q9, answers.shape[1]):
    #unique_per_question = set()
    #for answer in answers[:,index]:
        #unique_per_question.add(answer)
    #unique_answers2.append(list(unique_per_question))
#print(unique_answers2)

['2-4x par Sem.', '5-6x par Sem.', '4-5x par Jour', '6x par Jour', 'Jamais ou <1/Mois', '1-3x par Mois', '1x par Sem.', '2-3x par Jour', '1x par Jour']

In [6]:
#Valeurs numériques attribuées aux réponses : portions par semaine
dict_portions = { 0 : 0,
            '6x par Jour': 6*7, 
            '5-6x par Sem.' : 5.5, 
            '1x par Sem.' : 1, 
            '2-4x par Sem.' : 3,
            'Jamais ou <1/Mois' : 0,
            '2-3x par Jour' : 2.5*7,
            '4-5x par Jour' : 4.5*7, 
            '1-3x par Mois' : 2/4, 
            '1x par Jour' : 7 }

#Création d'un nouveau tableau avec les valeurs de portions par semaine
portions = []
for index in range(answers.shape[0]):
    portions_per_question = []
    for answer in answers[index,:]:
        portions_per_question.append(dict_portions[answer])
    portions.append(portions_per_question)
portions = np.array(portions)
portions #Lignes = personnes, Colonnes = questions

array([[1. , 1. , 3. , ..., 0.5, 0. , 0. ],
       [0. , 0. , 0.5, ..., 0.5, 5.5, 0.5],
       [0.5, 0. , 0. , ..., 1. , 3. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 3. , 5.5, 1. ],
       [0. , 0. , 7. , ..., 0. , 0. , 0. ],
       [3. , 0. , 5.5, ..., 1. , 1. , 0. ]])

In [8]:
#Load le fichier excel des taux
data_calories = pd.read_excel('taux.xlsx', sheet_name = "AFTER CONV")
data_calories = data_calories["Energie [kcal]"]
data_calories

0     162.50
1     105.00
2      86.25
3      73.00
4     396.00
       ...
81      0.00
82    182.50
83    182.50
84    138.60
85     48.40
Name: Energie [kcal], Length: 86, dtype: float64

In [9]:
calories = np.array(data_calories)
calories = calories.reshape(-1)

#Quantité totale de calories par semaine par question en ug
total_per_question = portions * calories

#Quantité totale de calories par semaine en mg
total_per_week = total_per_question.sum(axis=1)

total_per_week

array([14822.775, 16183.375,  7787.27 , 10120.265, 12770.29 , 10594.15 ,
       15505.735, 12739.375, 13429.1  , 23022.79 , 12174.515, 10593.61 ,
       10901.225,  7033.235, 15737.085, 18498.915, 18643.575, 21642.04 ,
       11046.62 ,  7348.895, 11146.28 ,  7108.69 , 15275.505, 12856.035,
        7911.14 , 11480.08 , 11647.46 , 12682.465, 24457.385, 14881.   ,
        6648.7  , 13227.545,  9878.46 , 11863.175,  7092.425, 10446.95 ,
       40740.27 , 11898.695,  6557.975, 15256.83 , 11579.28 , 10738.27 ,
       13330.395, 10572.55 , 16521.335, 12857.965,  4301.77 , 14503.91 ,
        6096.92 , 11006.865,  7935.965,  6112.22 , 16366.12 , 16703.545,
        8268.925,  9782.84 , 16606.66 ,  9468.22 ,  8930.87 , 13431.95 ,
       12638.53 ,  9874.15 , 10140.02 , 15097.305,  9229.5  , 11720.15 ,
       14485.04 ,  7233.25 ,  7915.825, 11342.025,  8662.52 , 11019.945,
       12880.695, 11153.655,  9603.295, 17400.41 , 10517.42 , 15297.725])

In [10]:
cid_to_calories = {'CID': data.CID[1:], 'Calories par semaine [kcal]': total_per_week}
df_cid_to_calories = pd.DataFrame(data = cid_to_calories).set_index('CID')
df_cid_to_calories

     Calories par semaine [kcal]
CID
066                    14822.775
074                    16183.375
061                     7787.270
092                    10120.265
002                    12770.290
..                           ...
024                    11153.655
097                     9603.295
094                    17400.410
004                    10517.420
073                    15297.725

[78 rows x 1 columns]

In [11]:
#Convert file to excel
df_cid_to_calories.to_excel('calories_scoring.xlsx')