In [1]:
import pandas as pd
import numpy as np

In [2]:
##Load le fichier excel des réponses
data = pd.read_excel("FFQ.xlsx")
data

,CID,Q1_1,Q1_2,Q1_3,Q1_4,Q1_5,Q1_6,Q2_1,Q2_2,Q2_3,...,Q23_3,Q23_4,Q23_5,Q23_6,Q23_7,Q23_8,Q23_9,Q23_10,Q23_11,Q23_12
0,CID,1) Lait et produit laitiers - Lait entier (0.2...,1) Lait et produit laitiers - Lait écrémé (0.2...,1) Lait et produit laitiers - Yaourt (125 g),1) Lait et produit laitiers - Quark (100 g),1) Lait et produit laitiers - Fromage (100 g),1) Lait et produit laitiers - Crème (20 g),Fruits - Raisins ou raisins secs (100 g),Fruits - Pomme ou poire (1 portion),"Fruits - Pêche, abricot (1 portion)",...,Par rapport aux vitamines de substitution: - P...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - A...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - S...
1,066,1x par Sem.,1x par Sem.,2-4x par Sem.,2-4x par Sem.,2-4x par Sem.,Jamais ou <1/Mois,2-4x par Sem.,5-6x par Sem.,1-3x par Mois,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,074,Jamais ou <1/Mois,Jamais ou <1/Mois,1-3x par Mois,Jamais ou <1/Mois,1x par Jour,2-4x par Sem.,2-4x par Sem.,Jamais ou <1/Mois,Jamais ou <1/Mois,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,061,1-3x par Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,2-4x par Sem.,Jamais ou <1/Mois,2-4x par Sem.,1-3x par Mois,1x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,092,Jamais ou <1/Mois,1x par Sem.,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,2-4x par Sem.,1x par Jour,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,024,1x par Jour,Jamais ou <1/Mois,1-3x par Mois,Jamais ou <1/Mois,2-4x par Sem.,1-3x par Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,097,1x par Sem.,2-4x par Sem.,2-4x par Sem.,2-4x par Sem.,2-4x par Sem.,2-4x par Sem.,Jamais ou <1/Mois,1x par Sem.,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,094,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,2-4x par Sem.,2-4x par Sem.,1-3x par Mois,5-6x par Sem.,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,004,Jamais ou <1/Mois,Jamais ou <1/Mois,1x par Jour,Jamais ou <1/Mois,2-4x par Sem.,Jamais ou <1/Mois,1-3x par Mois,5-6x par Sem.,Jamais ou <1/Mois,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,073,2-4x par Sem.,Jamais ou <1/Mois,5-6x par Sem.,Jamais ou <1/Mois,2-4x par Sem.,1x par Sem.,Jamais ou <1/Mois,1x par Sem.,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
##Isoler les valeurs
answers = data.iloc[1:, 1:]
answers = answers.fillna(0)
answers = np.array(answers)

##Réponses différentes par question

#Trouver la question 9 (questions non-analysées après)
q9 = data.iloc[0].index.tolist().index('Q9') #nom de la colonne

#Questions 1-8
answers = data.iloc[1:, 1:q9]
answers = answers.fillna(0)
answers = np.array(answers)
answers_flat = answers.reshape(-1)
unique_answers1 = set()
for answer in answers_flat:
    unique_answers1.add(answer)
unique_answers1 = list(unique_answers1)
print(unique_answers1)

#Questions 9-23
#unique_answers2 = []
#for index in range(q9, answers.shape[1]):
    #unique_per_question = set()
    #for answer in answers[:,index]:
        #unique_per_question.add(answer)
    #unique_answers2.append(list(unique_per_question))
#print(unique_answers2)

['2-3x par Jour', 'Jamais ou <1/Mois', '1-3x par Mois', '5-6x par Sem.', '4-5x par Jour', '1x par Jour', '2-4x par Sem.', '1x par Sem.', '6x par Jour']

In [8]:
#Valeurs numériques attribuées aux réponses : portions par semaine
dict_portions = { 0 : 0,
            '6x par Jour': 6*7, 
            '5-6x par Sem.' : 5.5, 
            '1x par Sem.' : 1, 
            '2-4x par Sem.' : 3,
            'Jamais ou <1/Mois' : 0,
            '2-3x par Jour' : 2.5*7,
            '4-5x par Jour' : 4.5*7, 
            '1-3x par Mois' : 2/4, 
            '1x par Jour' : 7 }

#Création d'un nouveau tableau avec les valeurs de portions par semaine
portions = []
for index in range(answers.shape[0]):
    portions_per_question = []
    for answer in answers[index,:]:
        portions_per_question.append(dict_portions[answer])
    portions.append(portions_per_question)
portions = np.array(portions)
portions #Lignes = personnes, Colonnes = questions

array([[1. , 1. , 3. , ..., 0.5, 0. , 0. ],
       [0. , 0. , 0.5, ..., 0.5, 5.5, 0.5],
       [0.5, 0. , 0. , ..., 1. , 3. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 3. , 5.5, 1. ],
       [0. , 0. , 7. , ..., 0. , 0. , 0. ],
       [3. , 0. , 5.5, ..., 1. , 1. , 0. ]])

In [10]:
#Load le fichier excel des taux
data_Omega3 = pd.read_excel('taux.xlsx', sheet_name = "AFTER CONV")
data_Omega3 = data_Omega3["Taux d'oméga 3 [mg]"]
data_Omega3

0      62.5
1       7.5
2      75.0
3       3.0
4     435.0
      ...
81      0.0
82      0.0
83      0.0
84      0.0
85      0.0
Name: Taux d'oméga 3 [mg], Length: 86, dtype: float64

In [11]:
Omega3 = np.array(data_Omega3)
Omega3 = Omega3.reshape(-1)

#Quantité totale de tryptophane par semaine par question en ug
total_per_question = portions * Omega3

#Quantité totale de tryptophane par semaine en mg
total_per_week = total_per_question.sum(axis=1)

total_per_week

array([11283.335, 12559.58 ,  6339.06 , 14229.07 , 10314.   ,  7965.855,
       10780.685, 10205.835, 13189.275, 15012.22 , 13827.425, 11305.525,
       10228.685,  6529.005, 14044.68 , 16527.54 , 13678.155, 34798.5  ,
       20376.085,  6905.59 , 10809.265,  7308.07 , 13529.615,  9632.05 ,
        7658.995,  5569.32 ,  9384.785, 17874.97 , 21706.425, 12943.08 ,
        8480.135, 18092.665,  5205.565,  9244.86 ,  9403.005, 19052.83 ,
       60281.16 , 12275.685,  4905.375,  9653.5  , 15440.84 , 16669.81 ,
       10922.01 , 10624.885, 12886.55 , 13954.78 ,  3857.51 , 13947.305,
        4337.09 , 12021.525, 13847.745,  8384.46 , 17400.215, 15392.44 ,
        7326.58 ,  9000.55 , 18141.61 ,  9720.265,  6250.04 , 11543.6  ,
       13830.17 ,  7415.035,  5934.065, 16393.485, 17077.375, 10105.255,
       11511.54 ,  6395.16 ,  6823.705, 10138.36 ,  8193.04 ,  8973.41 ,
       11735.495, 12076.775, 10021.345, 12634.11 ,  8294.29 , 13620.085])

In [13]:
cid_to_Omega3 = {'CID': data.CID[1:], 'Omégas 3 par semaine [mg]': total_per_week}
df_cid_to_Omega3 = pd.DataFrame(data = cid_to_Omega3).set_index('CID')
df_cid_to_Omega3

     Omégas 3 par semaine [mg]
CID
066                  11283.335
074                  12559.580
061                   6339.060
092                  14229.070
002                  10314.000
..                         ...
024                  12076.775
097                  10021.345
094                  12634.110
004                   8294.290
073                  13620.085

[78 rows x 1 columns]

In [14]:
#Convert file to excel
df_cid_to_Omega3.to_excel('Omega3_scoring.xlsx')