In [1]:
import pandas as pd
import numpy as np

In [2]:
##Load le fichier excel des réponses
data = pd.read_excel("FFQ.xlsx")
data

,CID,Q1_1,Q1_2,Q1_3,Q1_4,Q1_5,Q1_6,Q2_1,Q2_2,Q2_3,...,Q23_3,Q23_4,Q23_5,Q23_6,Q23_7,Q23_8,Q23_9,Q23_10,Q23_11,Q23_12
0,CID,1) Lait et produit laitiers - Lait entier (0.2...,1) Lait et produit laitiers - Lait écrémé (0.2...,1) Lait et produit laitiers - Yaourt (125 g),1) Lait et produit laitiers - Quark (100 g),1) Lait et produit laitiers - Fromage (100 g),1) Lait et produit laitiers - Crème (20 g),Fruits - Raisins ou raisins secs (100 g),Fruits - Pomme ou poire (1 portion),"Fruits - Pêche, abricot (1 portion)",...,Par rapport aux vitamines de substitution: - P...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - A...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - S...
1,066,1x par Sem.,1x par Sem.,2-4x par Sem.,2-4x par Sem.,2-4x par Sem.,Jamais ou <1/Mois,2-4x par Sem.,5-6x par Sem.,1-3x par Mois,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,074,Jamais ou <1/Mois,Jamais ou <1/Mois,1-3x par Mois,Jamais ou <1/Mois,1x par Jour,2-4x par Sem.,2-4x par Sem.,Jamais ou <1/Mois,Jamais ou <1/Mois,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,061,1-3x par Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,2-4x par Sem.,Jamais ou <1/Mois,2-4x par Sem.,1-3x par Mois,1x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,092,Jamais ou <1/Mois,1x par Sem.,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,2-4x par Sem.,1x par Jour,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,024,1x par Jour,Jamais ou <1/Mois,1-3x par Mois,Jamais ou <1/Mois,2-4x par Sem.,1-3x par Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,097,1x par Sem.,2-4x par Sem.,2-4x par Sem.,2-4x par Sem.,2-4x par Sem.,2-4x par Sem.,Jamais ou <1/Mois,1x par Sem.,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,094,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,2-4x par Sem.,2-4x par Sem.,1-3x par Mois,5-6x par Sem.,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,004,Jamais ou <1/Mois,Jamais ou <1/Mois,1x par Jour,Jamais ou <1/Mois,2-4x par Sem.,Jamais ou <1/Mois,1-3x par Mois,5-6x par Sem.,Jamais ou <1/Mois,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,073,2-4x par Sem.,Jamais ou <1/Mois,5-6x par Sem.,Jamais ou <1/Mois,2-4x par Sem.,1x par Sem.,Jamais ou <1/Mois,1x par Sem.,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
##Isoler les valeurs
answers = data.iloc[1:, 1:]
answers = answers.fillna(0)
answers = np.array(answers)

##Réponses différentes par question

#Trouver la question 9 (questions non-analysées après)
q9 = data.iloc[0].index.tolist().index('Q9') #nom de la colonne

#Questions 1-8
answers = data.iloc[1:, 1:q9]
answers = answers.fillna(0)
answers = np.array(answers)
answers_flat = answers.reshape(-1)
unique_answers1 = set()
for answer in answers_flat:
    unique_answers1.add(answer)
unique_answers1 = list(unique_answers1)
print(unique_answers1)

#Questions 9-23
#unique_answers2 = []
#for index in range(q9, answers.shape[1]):
    #unique_per_question = set()
    #for answer in answers[:,index]:
        #unique_per_question.add(answer)
    #unique_answers2.append(list(unique_per_question))
#print(unique_answers2)

['2-3x par Jour', '1x par Sem.', '1x par Jour', '6x par Jour', '1-3x par Mois', '5-6x par Sem.', '4-5x par Jour', '2-4x par Sem.', 'Jamais ou <1/Mois']

In [4]:
#Valeurs numériques attribuées aux réponses : portions par semaine
dict_portions = { 0 : 0,
            '6x par Jour': 6*7, 
            '5-6x par Sem.' : 5.5, 
            '1x par Sem.' : 1, 
            '2-4x par Sem.' : 3,
            'Jamais ou <1/Mois' : 0,
            '2-3x par Jour' : 2.5*7,
            '4-5x par Jour' : 4.5*7, 
            '1-3x par Mois' : 2/4, 
            '1x par Jour' : 7 }

#Création d'un nouveau tableau avec les valeurs de portions par semaine
portions = []
for index in range(answers.shape[0]):
    portions_per_question = []
    for answer in answers[index,:]:
        portions_per_question.append(dict_portions[answer])
    portions.append(portions_per_question)
portions = np.array(portions)
portions #Lignes = personnes, Colonnes = questions

array([[1. , 1. , 3. , ..., 0.5, 0. , 0. ],
       [0. , 0. , 0.5, ..., 0.5, 5.5, 0.5],
       [0.5, 0. , 0. , ..., 1. , 3. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 3. , 5.5, 1. ],
       [0. , 0. , 7. , ..., 0. , 0. , 0. ],
       [3. , 0. , 5.5, ..., 1. , 1. , 0. ]])

In [5]:
#Load le fichier excel des taux
data_Glu = pd.read_excel('taux.xlsx', sheet_name = "AFTER CONV")
data_Glu = data_Glu["Taux d'acide glutama [mg]"]
data_Glu

0     1762.5
1     2020.0
2      860.0
3     2657.0
4     5638.0
       ...
81       0.0
82      82.5
83      82.5
84     339.9
85       0.0
Name: Taux d'acide glutama [mg], Length: 86, dtype: float64

In [6]:
Glu = np.array(data_Glu)
Glu = Glu.reshape(-1)

#Quantité totale de glutamate par semaine par question en ug
total_per_question = portions * Glu

#Quantité totale de glutamate par semaine en mg
total_per_week = total_per_question.sum(axis=1)

total_per_week

array([118439.825, 124744.43 ,  68241.38 ,  53458.725, 110010.68 ,
        86093.68 , 132777.345, 100863.22 , 117148.05 , 166689.29 ,
       123913.49 ,  90563.245,  85980.2  ,  65107.255, 120467.95 ,
       158445.38 , 154194.18 , 226822.09 , 100577.305,  53085.46 ,
        95929.57 ,  59157.375, 124697.145,  98162.85 ,  73239.4  ,
        72798.325,  90364.05 , 104696.46 , 191426.05 , 116659.655,
        57688.325, 130326.05 ,  63057.875,  76093.2  ,  59518.98 ,
       157793.455, 290564.695, 109355.205,  43665.475, 108007.605,
        83554.45 ,  96182.42 ,  95180.095, 109329.675, 114829.525,
        88779.545,  38760.745, 142397.545,  56364.95 ,  67184.005,
        78621.545,  51128.56 , 152362.6  , 127560.75 ,  74122.73 ,
       101667.67 , 168114.745,  74192.55 ,  71275.025, 131778.215,
        93517.715,  49341.935,  47135.875, 125012.395,  64636.74 ,
        97223.795, 112624.38 ,  50734.125,  46520.65 ,  96135.645,
        86782.29 ,  43128.655,  91917.825,  96481.045,  97003.555,
       127854.7  ,  82464.195, 104810.445])

In [9]:
cid_to_Glu = {'CID': data.CID[1:], 'Glutamate par semaine [mg]': total_per_week}
df_cid_to_Glu = pd.DataFrame(data = cid_to_Glu).set_index('CID')
df_cid_to_Glu

     Glutamate par semaine [mg]
CID
066                  118439.825
074                  124744.430
061                   68241.380
092                   53458.725
002                  110010.680
..                          ...
024                   96481.045
097                   97003.555
094                  127854.700
004                   82464.195
073                  104810.445

[78 rows x 1 columns]

In [10]:
#Convert file to excel
df_cid_to_Glu.to_excel('Glutamate_scoring.xlsx')