In [1]:
import pandas as pd
import numpy as np

In [4]:
##Load le fichier excel des réponses
data = pd.read_excel("FFQ.xlsx")
data

,CID,Q1_1,Q1_2,Q1_3,Q1_4,Q1_5,Q1_6,Q2_1,Q2_2,Q2_3,...,Q23_3,Q23_4,Q23_5,Q23_6,Q23_7,Q23_8,Q23_9,Q23_10,Q23_11,Q23_12
0,CID,1) Lait et produit laitiers - Lait entier (0.2...,1) Lait et produit laitiers - Lait écrémé (0.2...,1) Lait et produit laitiers - Yaourt (125 g),1) Lait et produit laitiers - Quark (100 g),1) Lait et produit laitiers - Fromage (100 g),1) Lait et produit laitiers - Crème (20 g),Fruits - Raisins ou raisins secs (100 g),Fruits - Pomme ou poire (1 portion),"Fruits - Pêche, abricot (1 portion)",...,Par rapport aux vitamines de substitution: - P...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - A...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - S...
1,066,1x par Sem.,1x par Sem.,2-4x par Sem.,2-4x par Sem.,2-4x par Sem.,Jamais ou <1/Mois,2-4x par Sem.,5-6x par Sem.,1-3x par Mois,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,074,Jamais ou <1/Mois,Jamais ou <1/Mois,1-3x par Mois,Jamais ou <1/Mois,1x par Jour,2-4x par Sem.,2-4x par Sem.,Jamais ou <1/Mois,Jamais ou <1/Mois,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,061,1-3x par Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,2-4x par Sem.,Jamais ou <1/Mois,2-4x par Sem.,1-3x par Mois,1x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,092,Jamais ou <1/Mois,1x par Sem.,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,2-4x par Sem.,1x par Jour,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,024,1x par Jour,Jamais ou <1/Mois,1-3x par Mois,Jamais ou <1/Mois,2-4x par Sem.,1-3x par Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,097,1x par Sem.,2-4x par Sem.,2-4x par Sem.,2-4x par Sem.,2-4x par Sem.,2-4x par Sem.,Jamais ou <1/Mois,1x par Sem.,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,094,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,2-4x par Sem.,2-4x par Sem.,1-3x par Mois,5-6x par Sem.,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,004,Jamais ou <1/Mois,Jamais ou <1/Mois,1x par Jour,Jamais ou <1/Mois,2-4x par Sem.,Jamais ou <1/Mois,1-3x par Mois,5-6x par Sem.,Jamais ou <1/Mois,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,073,2-4x par Sem.,Jamais ou <1/Mois,5-6x par Sem.,Jamais ou <1/Mois,2-4x par Sem.,1x par Sem.,Jamais ou <1/Mois,1x par Sem.,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
##Isoler les valeurs
answers = data.iloc[1:, 1:]
answers = answers.fillna(0)
answers = np.array(answers)

##Réponses différentes par question

#Trouver la question 9 (questions non-analysées après)
q9 = data.iloc[0].index.tolist().index('Q9') #nom de la colonne

#Questions 1-8
answers = data.iloc[1:, 1:q9]
answers = answers.fillna(0)
answers = np.array(answers)
answers_flat = answers.reshape(-1)
unique_answers1 = set()
for answer in answers_flat:
    unique_answers1.add(answer)
unique_answers1 = list(unique_answers1)
print(unique_answers1)

#Questions 9-23
#unique_answers2 = []
#for index in range(q9, answers.shape[1]):
    #unique_per_question = set()
    #for answer in answers[:,index]:
        #unique_per_question.add(answer)
    #unique_answers2.append(list(unique_per_question))
#print(unique_answers2)

['4-5x par Jour', '2-4x par Sem.', '5-6x par Sem.', '2-3x par Jour', '1x par Jour', 'Jamais ou <1/Mois', '6x par Jour', '1x par Sem.', '1-3x par Mois']

In [8]:
#Valeurs numériques attribuées aux réponses : portions par semaine
dict_portions = { 0 : 0,
            '6x par Jour': 6*7, 
            '5-6x par Sem.' : 5.5, 
            '1x par Sem.' : 1, 
            '2-4x par Sem.' : 3,
            'Jamais ou <1/Mois' : 0,
            '2-3x par Jour' : 2.5*7,
            '4-5x par Jour' : 4.5*7, 
            '1-3x par Mois' : 2/4, 
            '1x par Jour' : 7 }

#Création d'un nouveau tableau avec les valeurs de portions par semaine
portions = []
for index in range(answers.shape[0]):
    portions_per_question = []
    for answer in answers[index,:]:
        portions_per_question.append(dict_portions[answer])
    portions.append(portions_per_question)
portions = np.array(portions)
portions #Lignes = personnes, Colonnes = questions

array([[1. , 1. , 3. , ..., 0.5, 0. , 0. ],
       [0. , 0. , 0.5, ..., 0.5, 5.5, 0.5],
       [0.5, 0. , 0. , ..., 1. , 3. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 3. , 5.5, 1. ],
       [0. , 0. , 7. , ..., 0. , 0. , 0. ],
       [3. , 0. , 5.5, ..., 1. , 1. , 0. ]])

In [10]:
#Load le fichier excel des taux de niacine
data_niacine = pd.read_excel('taux de niacine.xlsx')
data_niacine

                            Question  Taux de niacine [mg]
0   Full cream milk 0.25 l = 275,5 g              0.239685
1         Skim milk 0.25 l = 255,5 g              0.235060
2                      Yoghurt 125 g              0.112500
3                         Curd 100 g              0.150000
4                       Cheese 100 g              0.416000
..                               ...                   ...
81       Mineral water 1/4 l = 250 g              0.000000
82            Red wine 1/4 l = 400 g              0.400000
83          White wine 1/4 l = 400 g              0.400000
84               Beer 0,33 l = 300 g              2.310000
85    Liquor, Schnapps (brandy) 2 cl              0.000000

[86 rows x 2 columns]

In [11]:
niacine = data_niacine.iloc[:, 1:]
niacine = np.array(niacine)
niacine = niacine.reshape(-1)

#Quantité totale de niacine par semaine par question en ug
total_per_question = portions * niacine

#Quantité totale de niacine par semaine en mg
total_per_week = total_per_question.sum(axis=1)

total_per_week

array([187.52762  ,  95.72605  ,  70.4650175,  87.859235 , 147.104145 ,
        91.510275 , 136.90562  ,  96.893135 , 214.73005  , 147.674835 ,
       112.60519  , 112.069125 ,  81.92928  ,  37.851245 , 142.94905  ,
       178.38583  , 155.3650675, 214.00478  , 127.824475 ,  63.001    ,
       121.38245  ,  76.4548   , 171.74698  , 109.38337  ,  73.50253  ,
        86.89523  ,  93.8657425, 132.71295  , 156.7614675, 149.938045 ,
        54.82978  , 124.561075 ,  82.242    , 147.111075 ,  46.015455 ,
       161.8681175, 201.391675 , 103.39702  ,  67.8261   ,  89.503725 ,
       101.901425 , 117.896675 , 106.0237175,  98.874605 , 119.04865  ,
       120.44235  ,  27.526425 , 146.432705 ,  35.66537  ,  77.654385 ,
        94.6245675,  63.58654  , 142.38552  , 125.817635 ,  68.34828  ,
        93.3721925, 181.93823  ,  69.730655 ,  44.978255 , 107.3227   ,
       108.306855 ,  76.030025 ,  44.11875  ,  69.46822  ,  65.789575 ,
       108.309705 ,  68.2545675,  64.112205 ,  52.6797   , 104.94948  ,
       121.998675 ,  65.42693  ,  80.77487  , 111.20082  ,  92.17519  ,
       160.667875 ,  81.2072   , 155.225655 ])

In [13]:
cid_to_niacine = {'CID': data.CID[1:], 'Niacine par semaine [ug]': total_per_week}
df_cid_to_niacine = pd.DataFrame(data = cid_to_niacine).set_index('CID')
df_cid_to_niacine

     Niacine par semaine [ug]
CID
066                187.527620
074                 95.726050
061                 70.465017
092                 87.859235
002                147.104145
..                        ...
024                111.200820
097                 92.175190
094                160.667875
004                 81.207200
073                155.225655

[78 rows x 1 columns]

In [14]:
#Convert file to excel
df_cid_to_niacine.to_excel('niacine_scoring.xlsx')