In [1]:
import pandas as pd
import numpy as np

In [2]:
##Load le fichier excel des réponses
data = pd.read_excel("FFQ.xlsx")
data

,CID,Q1_1,Q1_2,Q1_3,Q1_4,Q1_5,Q1_6,Q2_1,Q2_2,Q2_3,...,Q23_3,Q23_4,Q23_5,Q23_6,Q23_7,Q23_8,Q23_9,Q23_10,Q23_11,Q23_12
0,CID,1) Lait et produit laitiers - Lait entier (0.2...,1) Lait et produit laitiers - Lait écrémé (0.2...,1) Lait et produit laitiers - Yaourt (125 g),1) Lait et produit laitiers - Quark (100 g),1) Lait et produit laitiers - Fromage (100 g),1) Lait et produit laitiers - Crème (20 g),Fruits - Raisins ou raisins secs (100 g),Fruits - Pomme ou poire (1 portion),"Fruits - Pêche, abricot (1 portion)",...,Par rapport aux vitamines de substitution: - P...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - A...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - S...
1,066,1x par Sem.,1x par Sem.,2-4x par Sem.,2-4x par Sem.,2-4x par Sem.,Jamais ou <1/Mois,2-4x par Sem.,5-6x par Sem.,1-3x par Mois,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,074,Jamais ou <1/Mois,Jamais ou <1/Mois,1-3x par Mois,Jamais ou <1/Mois,1x par Jour,2-4x par Sem.,2-4x par Sem.,Jamais ou <1/Mois,Jamais ou <1/Mois,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,061,1-3x par Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,2-4x par Sem.,Jamais ou <1/Mois,2-4x par Sem.,1-3x par Mois,1x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,092,Jamais ou <1/Mois,1x par Sem.,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,2-4x par Sem.,1x par Jour,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,024,1x par Jour,Jamais ou <1/Mois,1-3x par Mois,Jamais ou <1/Mois,2-4x par Sem.,1-3x par Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,097,1x par Sem.,2-4x par Sem.,2-4x par Sem.,2-4x par Sem.,2-4x par Sem.,2-4x par Sem.,Jamais ou <1/Mois,1x par Sem.,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,094,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,2-4x par Sem.,2-4x par Sem.,1-3x par Mois,5-6x par Sem.,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,004,Jamais ou <1/Mois,Jamais ou <1/Mois,1x par Jour,Jamais ou <1/Mois,2-4x par Sem.,Jamais ou <1/Mois,1-3x par Mois,5-6x par Sem.,Jamais ou <1/Mois,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,073,2-4x par Sem.,Jamais ou <1/Mois,5-6x par Sem.,Jamais ou <1/Mois,2-4x par Sem.,1x par Sem.,Jamais ou <1/Mois,1x par Sem.,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
##Isoler les valeurs
answers = data.iloc[1:, 1:]
answers = answers.fillna(0)
answers = np.array(answers)

##Réponses différentes par question

#Trouver la question 9 (questions non-analysées après)
q9 = data.iloc[0].index.tolist().index('Q9') #nom de la colonne

#Questions 1-8
answers = data.iloc[1:, 1:q9]
answers = answers.fillna(0)
answers = np.array(answers)
answers_flat = answers.reshape(-1)
unique_answers1 = set()
for answer in answers_flat:
    unique_answers1.add(answer)
unique_answers1 = list(unique_answers1)
print(unique_answers1)

#Questions 9-23
#unique_answers2 = []
#for index in range(q9, answers.shape[1]):
    #unique_per_question = set()
    #for answer in answers[:,index]:
        #unique_per_question.add(answer)
    #unique_answers2.append(list(unique_per_question))
#print(unique_answers2)

['2-3x par Jour', '1x par Jour', '6x par Jour', 'Jamais ou <1/Mois', '4-5x par Jour', '1-3x par Mois', '5-6x par Sem.', '1x par Sem.', '2-4x par Sem.']

In [4]:
#Valeurs numériques attribuées aux réponses : portions par semaine
dict_portions = { 0 : 0,
            '6x par Jour': 6*7, 
            '5-6x par Sem.' : 5.5, 
            '1x par Sem.' : 1, 
            '2-4x par Sem.' : 3,
            'Jamais ou <1/Mois' : 0,
            '2-3x par Jour' : 2.5*7,
            '4-5x par Jour' : 4.5*7, 
            '1-3x par Mois' : 2/4, 
            '1x par Jour' : 7 }

#Création d'un nouveau tableau avec les valeurs de portions par semaine
portions = []
for index in range(answers.shape[0]):
    portions_per_question = []
    for answer in answers[index,:]:
        portions_per_question.append(dict_portions[answer])
    portions.append(portions_per_question)
portions = np.array(portions)
portions #Lignes = personnes, Colonnes = questions

array([[1. , 1. , 3. , ..., 0.5, 0. , 0. ],
       [0. , 0. , 0.5, ..., 0.5, 5.5, 0.5],
       [0.5, 0. , 0. , ..., 1. , 3. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 3. , 5.5, 1. ],
       [0. , 0. , 7. , ..., 0. , 0. , 0. ],
       [3. , 0. , 5.5, ..., 1. , 1. , 0. ]])

In [6]:
#Load le fichier excel des taux de niacine
data_niacine = pd.read_excel('taux.xlsx')
data_niacine

#Load le fichier excel des taux
data_niacine = pd.read_excel('taux.xlsx', sheet_name = "AFTER CONV")
data_niacine = data_niacine["Taux de niacine [μg]"]
data_niacine

0      225.0
1      250.0
2      112.5
3      150.0
4      140.0
       ...
81       0.0
82     250.0
83     250.0
84    2541.0
85       0.0
Name: Taux de niacine [μg], Length: 86, dtype: float64

In [9]:
niacine = np.array(data_niacine)
niacine = niacine.reshape(-1)

#Quantité totale de niacine par semaine par question en ug
total_per_question = portions * niacine

#Quantité totale de niacine par semaine en mg
total_per_week = total_per_question.sum(axis=1)

total_per_week

array([177981.225,  94381.6  ,  67700.525,  71081.575, 137804.5  ,
        82495.575, 126552.5  ,  90354.6  , 205466.375, 137023.25 ,
        93649.575, 106441.325,  89049.35 ,  36431.1  , 141812.125,
       140692.5  , 140565.15 , 205072.9  , 132757.75 ,  50431.05 ,
        88933.475,  66639.95 , 147296.775, 105460.825,  62991.225,
        80606.5  ,  75746.025, 122639.475, 131828.9  , 130056.725,
        54337.125, 100279.95 ,  70846.475, 124616.225,  39206.675,
       178707.775, 188456.7  , 100736.925,  66083.325,  85475.975,
        86002.475, 117164.875, 103308.975, 101879.75 ,  99280.925,
       120040.225,  18657.625, 150993.15 ,  36602.4  ,  73274.2  ,
        92313.55 ,  48811.525, 120925.35 , 128656.25 ,  64189.575,
        88626.35 , 161753.65 ,  62874.775,  39198.625,  95701.525,
       105590.65 ,  69008.85 ,  42016.625,  66011.025,  45632.925,
        99751.325,  61738.15 ,  61422.6  ,  49176.425,  97283.925,
       111093.85 ,  62099.85 ,  78525.375, 111613.1  ,  76328.725,
       150102.075,  81209.   , 151451.4  ])

In [10]:
cid_to_niacine = {'CID': data.CID[1:], 'Niacine par semaine [μg]': total_per_week}
df_cid_to_niacine = pd.DataFrame(data = cid_to_niacine).set_index('CID')
df_cid_to_niacine

     Niacine par semaine [μg]
CID
066                177981.225
074                 94381.600
061                 67700.525
092                 71081.575
002                137804.500
..                        ...
024                111613.100
097                 76328.725
094                150102.075
004                 81209.000
073                151451.400

[78 rows x 1 columns]

In [11]:
#Convert file to excel
df_cid_to_niacine.to_excel('niacine_scoring.xlsx')