In [1]:
import pandas as pd
import numpy as np

In [2]:
##Load le fichier excel des réponses
data = pd.read_excel("FFQ.xlsx")
data

,CID,Q1_1,Q1_2,Q1_3,Q1_4,Q1_5,Q1_6,Q2_1,Q2_2,Q2_3,...,Q23_3,Q23_4,Q23_5,Q23_6,Q23_7,Q23_8,Q23_9,Q23_10,Q23_11,Q23_12
0,CID,1) Lait et produit laitiers - Lait entier (0.2...,1) Lait et produit laitiers - Lait écrémé (0.2...,1) Lait et produit laitiers - Yaourt (125 g),1) Lait et produit laitiers - Quark (100 g),1) Lait et produit laitiers - Fromage (100 g),1) Lait et produit laitiers - Crème (20 g),Fruits - Raisins ou raisins secs (100 g),Fruits - Pomme ou poire (1 portion),"Fruits - Pêche, abricot (1 portion)",...,Par rapport aux vitamines de substitution: - P...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - A...,Par rapport aux vitamines de substitution: - V...,Par rapport aux vitamines de substitution: - S...
1,066,1x par Sem.,1x par Sem.,2-4x par Sem.,2-4x par Sem.,2-4x par Sem.,Jamais ou <1/Mois,2-4x par Sem.,5-6x par Sem.,1-3x par Mois,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,074,Jamais ou <1/Mois,Jamais ou <1/Mois,1-3x par Mois,Jamais ou <1/Mois,1x par Jour,2-4x par Sem.,2-4x par Sem.,Jamais ou <1/Mois,Jamais ou <1/Mois,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,061,1-3x par Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,2-4x par Sem.,Jamais ou <1/Mois,2-4x par Sem.,1-3x par Mois,1x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,092,Jamais ou <1/Mois,1x par Sem.,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,2-4x par Sem.,1x par Jour,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,024,1x par Jour,Jamais ou <1/Mois,1-3x par Mois,Jamais ou <1/Mois,2-4x par Sem.,1-3x par Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,097,1x par Sem.,2-4x par Sem.,2-4x par Sem.,2-4x par Sem.,2-4x par Sem.,2-4x par Sem.,Jamais ou <1/Mois,1x par Sem.,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,094,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,Jamais ou <1/Mois,2-4x par Sem.,2-4x par Sem.,1-3x par Mois,5-6x par Sem.,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,004,Jamais ou <1/Mois,Jamais ou <1/Mois,1x par Jour,Jamais ou <1/Mois,2-4x par Sem.,Jamais ou <1/Mois,1-3x par Mois,5-6x par Sem.,Jamais ou <1/Mois,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,073,2-4x par Sem.,Jamais ou <1/Mois,5-6x par Sem.,Jamais ou <1/Mois,2-4x par Sem.,1x par Sem.,Jamais ou <1/Mois,1x par Sem.,2-4x par Sem.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
##Isoler les valeurs
answers = data.iloc[1:, 1:]
answers = answers.fillna(0)
answers = np.array(answers)

##Réponses différentes par question

#Trouver la question 9 (questions non-analysées après)
q9 = data.iloc[0].index.tolist().index('Q9') #nom de la colonne

#Questions 1-8
answers = data.iloc[1:, 1:q9]
answers = answers.fillna(0)
answers = np.array(answers)
answers_flat = answers.reshape(-1)
unique_answers1 = set()
for answer in answers_flat:
    unique_answers1.add(answer)
unique_answers1 = list(unique_answers1)
print(unique_answers1)

#Questions 9-23
#unique_answers2 = []
#for index in range(q9, answers.shape[1]):
    #unique_per_question = set()
    #for answer in answers[:,index]:
        #unique_per_question.add(answer)
    #unique_answers2.append(list(unique_per_question))
#print(unique_answers2)

['4-5x par Jour', '1x par Sem.', '6x par Jour', '1-3x par Mois', '5-6x par Sem.', '1x par Jour', '2-3x par Jour', 'Jamais ou <1/Mois', '2-4x par Sem.']

In [4]:
#Valeurs numériques attribuées aux réponses : portions par semaine
dict_portions = { 0 : 0,
            '6x par Jour': 6*7, 
            '5-6x par Sem.' : 5.5, 
            '1x par Sem.' : 1, 
            '2-4x par Sem.' : 3,
            'Jamais ou <1/Mois' : 0,
            '2-3x par Jour' : 2.5*7,
            '4-5x par Jour' : 4.5*7, 
            '1-3x par Mois' : 2/4, 
            '1x par Jour' : 7 }

#Création d'un nouveau tableau avec les valeurs de portions par semaine
portions = []
for index in range(answers.shape[0]):
    portions_per_question = []
    for answer in answers[index,:]:
        portions_per_question.append(dict_portions[answer])
    portions.append(portions_per_question)
portions = np.array(portions)
portions #Lignes = personnes, Colonnes = questions

array([[1. , 1. , 3. , ..., 0.5, 0. , 0. ],
       [0. , 0. , 0.5, ..., 0.5, 5.5, 0.5],
       [0.5, 0. , 0. , ..., 1. , 3. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 3. , 5.5, 1. ],
       [0. , 0. , 7. , ..., 0. , 0. , 0. ],
       [3. , 0. , 5.5, ..., 1. , 1. , 0. ]])

In [5]:
#Load le fichier excel des taux de niacine
data_niacine = pd.read_excel('taux.xlsx')
data_niacine

#Load le fichier excel des taux
data_niacine = pd.read_excel('taux.xlsx', sheet_name = "AFTER CONV")
data_niacine = data_niacine["Taux d'équivalents de niacine [μg]"]
data_niacine

0     1725.00
1     2375.00
2      966.25
3     2800.00
4     6473.00
       ...
81       0.00
82     250.00
83     250.00
84    3144.90
85       0.00
Name: Taux d'équivalents de niacine [μg], Length: 86, dtype: float64

In [7]:
niacine = np.array(data_niacine)
niacine = niacine.reshape(-1)

#Quantité totale de niacine par semaine par question en ug
total_per_question = portions * niacine

#Quantité totale de niacine par semaine en mg
total_per_week = total_per_question.sum(axis=1)

total_per_week

array([292682.575, 228035.67 , 139946.095, 121861.45 , 252118.595,
       173875.095, 271115.93 , 201729.395, 348771.15 , 308895.01 ,
       229053.275, 196868.82 , 176245.75 , 106029.395, 275334.99 ,
       305971.42 , 305173.795, 444116.235, 245042.195,  99176.24 ,
       205794.28 , 128993.425, 281854.405, 202034.225, 145962.425,
       148471.85 , 170836.125, 242882.59 , 339380.1  , 262575.47 ,
       118253.2  , 247209.95 , 144729.825, 218911.725, 103527.495,
       367910.495, 518229.98 , 219627.595, 108162.125, 198025.77 ,
       173939.55 , 232897.505, 216837.03 , 236659.425, 211582.5  ,
       218246.32 ,  65676.38 , 300684.68 ,  95468.15 , 140824.895,
       175936.62 , 109555.87 , 294615.65 , 257864.6  , 139955.045,
       190907.555, 358627.245, 140013.575, 102719.725, 228569.485,
       208244.185, 116720.415,  86487.15 , 191990.43 , 112510.635,
       214542.505, 169508.095, 118033.85 ,  97744.515, 206706.245,
       211113.585, 110209.07 , 183936.865, 217415.305, 180967.92 ,
       290091.6  , 169921.295, 274443.42 ])

In [8]:
cid_to_niacine = {'CID': data.CID[1:], 'équivalents de niacine par semaine [μg]': total_per_week}
df_cid_to_niacine = pd.DataFrame(data = cid_to_niacine).set_index('CID')
df_cid_to_niacine

     équivalents de niacine par semaine [μg]
CID
066                               292682.575
074                               228035.670
061                               139946.095
092                               121861.450
002                               252118.595
..                                       ...
024                               217415.305
097                               180967.920
094                               290091.600
004                               169921.295
073                               274443.420

[78 rows x 1 columns]

In [9]:
#Convert file to excel
df_cid_to_niacine.to_excel('niacine_equivalents_scoring.xlsx')